---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS Kinesis controller is a service controller for managing Kinesis resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Kinesis
description: |-
  Manage Amazon Kinesis resources in AWS from within your Kubernetes cluster.


  **About Amazon Kinesis**


  You can use Amazon Kinesis Data Streams to collect and process large streams of data records in real time. You can create data-processing applications, known as Kinesis Data Streams applications. A typical Kinesis Data Streams application reads data from a data stream as data records. These applications can use the Kinesis Client Library, and they can run on Amazon EC2 instances.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.
samples:
- kind: Stream
  spec: '{}'
maintainers:
- name: "kinesis maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon Kinesis Developer Resources
  url: https://aws.amazon.com/kinesis/developer-resources/
